OnlineBookStore/src/java/jpa/entities/BillDetails.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import java.math.BigInteger;
import javax.persistence.Basic;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author kchandar
 */
@Entity
@Table(name = "BILL_DETAILS", catalog = "", schema = "BOOK_STORE")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "BillDetails.findAll", query = "SELECT b FROM BillDetails b"),
    @NamedQuery(name = "BillDetails.findByBillId", query = "SELECT b FROM BillDetails b WHERE b.billDetailsPK.billId = :billId"),
    @NamedQuery(name = "BillDetails.findByBookId", query = "SELECT b FROM BillDetails b WHERE b.billDetailsPK.bookId = :bookId"),
    @NamedQuery(name = "BillDetails.findByQuantity", query = "SELECT b FROM BillDetails b WHERE b.quantity = :quantity"),
    @NamedQuery(name = "BillDetails.findByPrice", query = "SELECT b FROM BillDetails b WHERE b.price = :price")})
public class BillDetails implements Serializable {

    private static final long serialVersionUID = 1L;
    @EmbeddedId
    protected BillDetailsPK billDetailsPK;
    @Basic(optional = false)
    @NotNull
    private BigInteger quantity;
    private BigInteger price;
    @JoinColumn(name = "BOOK_ID", referencedColumnName = "BOOK_ID", insertable = false, updatable = false)
    @ManyToOne(optional = false)
    private Book book;
    @JoinColumn(name = "BILL_ID", referencedColumnName = "BILL_ID", insertable = false, updatable = false)
    @ManyToOne(optional = false)
    private BookBill bookBill;

    public BillDetails() {
    }

    public BillDetails(BillDetailsPK billDetailsPK) {
        this.billDetailsPK = billDetailsPK;
    }

    public BillDetails(BillDetailsPK billDetailsPK, BigInteger quantity) {
        this.billDetailsPK = billDetailsPK;
        this.quantity = quantity;
    }

    public BillDetails(BigInteger billId, String bookId) {
        this.billDetailsPK = new BillDetailsPK(billId, bookId);
    }

    public BillDetailsPK getBillDetailsPK() {
        return billDetailsPK;
    }

    public void setBillDetailsPK(BillDetailsPK billDetailsPK) {
        this.billDetailsPK = billDetailsPK;
    }

    public BigInteger getQuantity() {
        return quantity;
    }

    public void setQuantity(BigInteger quantity) {
        this.quantity = quantity;
    }

    public BigInteger getPrice() {
        return price;
    }

    public void setPrice(BigInteger price) {
        this.price = price;
    }

    public Book getBook() {
        return book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public BookBill getBookBill() {
        return bookBill;
    }

    public void setBookBill(BookBill bookBill) {
        this.bookBill = bookBill;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (billDetailsPK != null ? billDetailsPK.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof BillDetails)) {
            return false;
        }
        BillDetails other = (BillDetails) object;
        if ((this.billDetailsPK == null && other.billDetailsPK != null) || (this.billDetailsPK != null && !this.billDetailsPK.equals(other.billDetailsPK))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.BillDetails[ billDetailsPK=" + billDetailsPK + " ]";
    }
    
}

OnlineBookStore/src/java/jsf/BillDetailsController.java
package jsf;

import jpa.entities.BillDetails;
import jsf.util.JsfUtil;
import jsf.util.JsfUtil.PersistAction;
import jpa.session.BillDetailsFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("billDetailsController")
@SessionScoped
public class BillDetailsController implements Serializable {

    @EJB
    private jpa.session.BillDetailsFacade ejbFacade;
    private List<BillDetails> items = null;
    private BillDetails selected;

    public BillDetailsController() {
    }

    public BillDetails getSelected() {
        return selected;
    }

    public void setSelected(BillDetails selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
        selected.getBillDetailsPK().setBookId(selected.getBook().getBookId());
//        selected.getBillDetailsPK().setBillId(selected.getBookBill().getBillId());
    }

    protected void initializeEmbeddableKey() {
        selected.setBillDetailsPK(new jpa.entities.BillDetailsPK());
    }

    private BillDetailsFacade getFacade() {
        return ejbFacade;
    }

    public BillDetails prepareCreate() {
        selected = new BillDetails();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("BillDetailsCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("BillDetailsUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("BillDetailsDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<BillDetails> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public BillDetails getBillDetails(jpa.entities.BillDetailsPK id) {
        return getFacade().find(id);
    }

    public List<BillDetails> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<BillDetails> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = BillDetails.class)
    public static class BillDetailsControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            BillDetailsController controller = (BillDetailsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "billDetailsController");
            return controller.getBillDetails(getKey(value));
        }

        jpa.entities.BillDetailsPK getKey(String value) {
            jpa.entities.BillDetailsPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new jpa.entities.BillDetailsPK();
//            key.setBillId(values[0]);
            key.setBookId(values[1]);
            return key;
        }

        String getStringKey(jpa.entities.BillDetailsPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getBillId());
            sb.append(SEPARATOR);
            sb.append(value.getBookId());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof BillDetails) {
                BillDetails o = (BillDetails) object;
                return getStringKey(o.getBillDetailsPK());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), BillDetails.class.getName()});
                return null;
            }
        }

    }

}

OnlineBookStore/web/billDetails/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="BillDetailsCreateDlg" widgetVar="BillDetailsCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateBillDetailsTitle}">
            <h:form id="BillDetailsCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{billDetailsController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateBillDetailsLabel_quantity}" for="quantity" />
                        <p:inputText id="quantity" value="#{billDetailsController.selected.quantity}" title="#{bundle.CreateBillDetailsTitle_quantity}" required="true" requiredMessage="#{bundle.CreateBillDetailsRequiredMessage_quantity}"/>
                        <p:outputLabel value="#{bundle.CreateBillDetailsLabel_price}" for="price" />
                        <p:inputText id="price" value="#{billDetailsController.selected.price}" title="#{bundle.CreateBillDetailsTitle_price}" />
                        <p:outputLabel value="#{bundle.CreateBillDetailsLabel_book}" for="book" />
                        <p:selectOneMenu id="book" value="#{billDetailsController.selected.book}" required="true" requiredMessage="#{bundle.EditBillDetailsRequiredMessage_book}">
                            <f:selectItems value="#{bookController.itemsAvailableSelectOne}"
                                           var="bookItem"
                                           itemValue="#{bookItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateBillDetailsLabel_bookBill}" for="bookBill" />
                        <p:selectOneMenu id="bookBill" value="#{billDetailsController.selected.bookBill}" required="true" requiredMessage="#{bundle.EditBillDetailsRequiredMessage_bookBill}">
                            <f:selectItems value="#{bookBillController.itemsAvailableSelectOne}"
                                           var="bookBillItem"
                                           itemValue="#{bookBillItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{billDetailsController.create}" value="#{bundle.Save}" update="display,:BillDetailsListForm:datalist,:growl" oncomplete="handleSubmit(args,'BillDetailsCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="BillDetailsCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

OnlineBookStore/web/billDetails/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="BillDetailsEditDlg" widgetVar="BillDetailsEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditBillDetailsTitle}">
            <h:form id="BillDetailsEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{billDetailsController.selected != null}">
                        <p:outputLabel value="#{bundle.EditBillDetailsLabel_quantity}" for="quantity" />
                        <p:inputText id="quantity" value="#{billDetailsController.selected.quantity}" title="#{bundle.EditBillDetailsTitle_quantity}" required="true" requiredMessage="#{bundle.EditBillDetailsRequiredMessage_quantity}"/>
                        <p:outputLabel value="#{bundle.EditBillDetailsLabel_price}" for="price" />
                        <p:inputText id="price" value="#{billDetailsController.selected.price}" title="#{bundle.EditBillDetailsTitle_price}" />
                        <p:outputLabel value="#{bundle.EditBillDetailsLabel_book}" for="book" />
                        <p:selectOneMenu id="book" value="#{billDetailsController.selected.book}" required="true" requiredMessage="#{bundle.EditBillDetailsRequiredMessage_book}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{bookController.itemsAvailableSelectOne}"
                                           var="bookItem"
                                           itemValue="#{bookItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditBillDetailsLabel_bookBill}" for="bookBill" />
                        <p:selectOneMenu id="bookBill" value="#{billDetailsController.selected.bookBill}" required="true" requiredMessage="#{bundle.EditBillDetailsRequiredMessage_bookBill}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{bookBillController.itemsAvailableSelectOne}"
                                           var="bookBillItem"
                                           itemValue="#{bookBillItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{billDetailsController.update}" value="#{bundle.Save}" update="display,:BillDetailsListForm:datalist,:growl" oncomplete="handleSubmit(args, 'BillDetailsEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="BillDetailsEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

OnlineBookStore/web/billDetails/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListBillDetailsTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="BillDetailsListForm">
                <p:panel header="#{bundle.ListBillDetailsTitle}">
                    <p:dataTable id="datalist" value="#{billDetailsController.items}" var="item"
                                 selectionMode="single" selection="#{billDetailsController.selected}"
                                 paginator="true"
                                 rowKey="#{item.billDetailsPK}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBillDetailsTitle_quantity}"/>
                            </f:facet>
                            <h:outputText value="#{item.quantity}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBillDetailsTitle_price}"/>
                            </f:facet>
                            <h:outputText value="#{item.price}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBillDetailsTitle_book}"/>
                            </f:facet>
                            <h:outputText value="#{item.book}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListBillDetailsTitle_bookBill}"/>
                            </f:facet>
                            <h:outputText value="#{item.bookBill}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{billDetailsController.prepareCreate}" update=":BillDetailsCreateForm" oncomplete="PF('BillDetailsCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":BillDetailsViewForm" oncomplete="PF('BillDetailsViewDialog').show()" disabled="#{empty billDetailsController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":BillDetailsEditForm" oncomplete="PF('BillDetailsEditDialog').show()" disabled="#{empty billDetailsController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{billDetailsController.destroy}" update=":growl,datalist" disabled="#{empty billDetailsController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

OnlineBookStore/web/billDetails/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="BillDetailsViewDlg" widgetVar="BillDetailsViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewBillDetailsTitle}">
            <h:form id="BillDetailsViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{billDetailsController.selected != null}">
                        <h:outputText value="#{bundle.ViewBillDetailsLabel_quantity}"/>
                        <h:outputText value="#{billDetailsController.selected.quantity}" title="#{bundle.ViewBillDetailsTitle_quantity}"/>
                        <h:outputText value="#{bundle.ViewBillDetailsLabel_price}"/>
                        <h:outputText value="#{billDetailsController.selected.price}" title="#{bundle.ViewBillDetailsTitle_price}"/>
                        <h:outputText value="#{bundle.ViewBillDetailsLabel_book}"/>
                        <h:outputText value="#{billDetailsController.selected.book}" title="#{bundle.ViewBillDetailsTitle_book}"/>
                        <h:outputText value="#{bundle.ViewBillDetailsLabel_bookBill}"/>
                        <h:outputText value="#{billDetailsController.selected.bookBill}" title="#{bundle.ViewBillDetailsTitle_bookBill}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="BillDetailsViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>